## [作業重點]
使用 Sklearn 中的 Lasso, Ridge 模型，來訓練各種資料集，務必了解送進去模型訓練的**資料型態**為何，也請了解模型中各項參數的意義。

機器學習的模型非常多種，但要訓練的資料多半有固定的格式，確保你了解訓練資料的格式為何，這樣在應用新模型時，就能夠最快的上手開始訓練！

## 練習時間
試著使用 sklearn datasets 的其他資料集 (boston, ...)，來訓練自己的線性迴歸模型，並加上適當的正則化來觀察訓練情形。

In [1]:
import numpy as np
from sklearn import datasets, linear_model
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score

In [4]:
boston = datasets.load_boston()
x_train, x_test, y_train, y_test = train_test_split(boston.data, boston.target, test_size = 0.1, random_state = 4)

In [24]:
lasso = linear_model.Lasso(alpha = 0.1)
lasso.fit(x_train, y_train)
y_pred = lasso.predict(x_test)
lasso.coef_

array([-0.11567831,  0.05152311, -0.03346275,  1.2230427 , -0.        ,
        3.53216363, -0.00922692, -1.19460642,  0.28775344, -0.01473748,
       -0.75732817,  0.01037228, -0.58007751])

In [25]:
print("Mean squared error: %.2f" % mean_squared_error(y_test, y_pred))

Mean squared error: 18.19


In [26]:
ridge = linear_model.Ridge(alpha = 0.1)
ridge.fit(x_train, y_train)
y_pred = ridge.predict(x_test)
ridge.coef_

array([-1.25305527e-01,  4.85968956e-02,  1.35490467e-02,  3.05965839e+00,
       -1.61558736e+01,  3.62646355e+00,  1.10808781e-03, -1.47693015e+00,
        3.17043498e-01, -1.28048402e-02, -9.15220623e-01,  9.56698213e-03,
       -5.35070934e-01])

In [27]:
print("Mean squared error: %.2f" %mean_squared_error(y_test, y_pred))

Mean squared error: 17.07


In [32]:
wine = datasets.load_wine()
# wine.target
x_train, x_test, y_train, y_test = train_test_split(wine.data, wine.target, test_size = 0.1, random_state = 4)

In [40]:
lasso = linear_model.Lasso(alpha = 0.1)
lasso.fit(x_train, y_train)
y_pred = lasso.predict(x_test)
lasso.coef_

array([-0.        ,  0.        , -0.        ,  0.02903446,  0.00036735,
       -0.        , -0.29879073,  0.        , -0.        ,  0.09727668,
       -0.        , -0.        , -0.00123357])

In [39]:
print("Mean squared error: %.2f" % mean_squared_error(y_test, y_pred))

Mean squared error: 0.07


In [36]:
ridge = linear_model.Ridge(alpha = 0.1)
ridge.fit(x_train, y_train)
y_pred = ridge.predict(x_test)
ridge.coef_

array([-1.04747678e-01,  2.93000101e-02, -1.78367204e-01,  4.30426463e-02,
        1.41525650e-04,  1.46625147e-01, -3.68355272e-01, -2.40726939e-01,
        4.17957485e-02,  7.48587578e-02, -1.56797641e-01, -2.63031694e-01,
       -7.45368953e-04])

In [37]:
print("Mean squared error: %.2f" % mean_squared_error(y_test, y_pred))

Mean squared error: 0.07
